name: smhi
description: A Dart wrapper of the SMHI Forecast API
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
