name: smhi
description: A Dart wrapper of the SMHI Open Data API
version: 1.0.0
homepage: https://github.com/Lucke0051/smhi

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  intl: ^0.17.0

dev_dependencies:
  lint: ^1.6.0
  test: ^1.17.12